# Generated by Django 4.2.6 on 2023-10-16 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='tdesig',
            field=models.TextField(default=datetime.datetime(2023, 10, 16, 8, 52, 21, 150887, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
