# Generated by Django 4.2.6 on 2023-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_teammember_tdesig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='tdesig',
            field=models.CharField(max_length=50),
        ),
    ]
