# Generated by Django 4.2.6 on 2023-10-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
